#!/bin/bash 

    java -classpath /home/federico/Scrivania/SATPlan/code/enhsp/src/:/home/federico/Scrivania/SATPlan/code/enhsp/libs/PPMaJal2.jar:/home/federico/Scrivania/SATPlan/code/enhsp/libs/* ENHSP "$@"
